name: Uploads OpenAPI spec to Stainless

on:
  push:
    branches: [main]

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Uploads OpenAPI spec to Stainless
        uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: "./openapi.yml"
          config_path: "./stainless-config.yml"
          project_name: 'oba'